### ISSUE TITLE
PA Review: Hosting on Heroku

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#2]
Initial Deployment:

- [x] Initial push to heroku

Final Deployment:

- [x] Remove console statements: debuggers, console.logs, errors, minification warnings, mixed content warnings
- [x] Use dev tools in dev environment

Bonus:
- [ ]  Custom domain name

**Comment by youknowhu** [comment]
@anastassia-b I have pushed to heroku! You can access Hippocampus Live  here https://camp-hippocampus.herokuapp.com or on my Wiki home page.

**Comment by anastassia-b** [comment]
@youknowhu The production version still has loggers. :)

**Comment by youknowhu** [comment]
@anastassia-b  Ah! i made a quick fix on something yesterday and forgot to clean up the loggers again -_-. 

Thanks for catching that. This should be all complete now!

**Comment by anastassia-b** [comment]
Awesome thank you! Great job!
