### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#3]
- [x]  Backend: DB, model, controller, views
- [x]  Redux Loop: ajax, actions, reducer
- [x]  Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by youknowhu** [comment]
@anastassia-b, 

This should be ready for review!  The back-end/primary functionality should all be working. I wanted to fine tune the clicking outside of modal experience (currently doesn't close), but everything else shoudl be good to go!

**Comment by youknowhu** [comment]
I also chose to only have a single login button, that someone can switch to sign up/just log in with a demo account. I didn't want to display two separate buttons, login/signup, I think its a little cleaner this way. Let me know if you have any concerns with this approach!

**Comment by youknowhu** [comment]
@anastassia-b OK i fixed the modal experience. I think I am pretty satisfied with the current user experience and I feel pretty good about the bug-free functionality (I think). I also may have pushed to heroku as an already logged in user.... please excuse that!

**Comment by anastassia-b** [comment]
Hey @youknowhu ! Great work on this feature. The functionality of logging in, signing up, and logging out is complete. I was able to make an account. Also, error handling functionality is excellent! It displays semantic errors per action, and the errors are cleared at the right time. 

The styling is on point as well. 
- [x] Maybe the only suggestion I have is not to hard code the padding around the `h2` that welcomes the guest, but instead to align it to the center of the nav bar. This can be done by adding `align-items: center` to the `nav-right` (after removing `padding-top` on `h2`).

Great job!

**Comment by youknowhu** [comment]
Awesome. I am moving your stylistic feedback to my own stylistic to do list.
