### ISSUE TITLE
PA Review: Listings 

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#4]
- [x] Users can view listing show page.
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by youknowhu** [comment]
@anastassia-b  I took out an MVP about the homepage of user listings per our conversation yesterday.

**Comment by youknowhu** [comment]
@anastassia-b this should be ready for you to review!

To visit the listing show page, you can click on the Glacier National Picture on the homepage, you can also visit the following links:
- https://camp-hippocampus.herokuapp.com/#/listings/5
- https://camp-hippocampus.herokuapp.com/#/listings/6


For styling, I did not take everything from HipCamp's show page, and will be adding the reviews and bookings components when I get to those features. Some of my styling is somewhat hard-coded, which I plan on doing a CSS clean up at the end (hopefully), to make it more responsive!

**Comment by anastassia-b** [comment]
Excellent work!! The homepage takes me to a project, and I've checked out the two you linked above. The functionality and design is great. I like the way you integrated google elevation api and open weather to fetch information per page. This MVP is complete!

The only other suggestions we mentioned are: 
- [ ] Slightly decreasing the font-size in the `vibe-square` to 2. 
- [ ] Adding more description icons to each listing. 
- [ ] Adding a 3rd image to each listing.
