### ISSUE TITLE
PA Review: Reviews

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#6]
- [x] Users can _read_ reviews for listings
- [x] Logged in users can _create_ reviews
- [x] Logged in users can _update_ their own reviews
- [x] Logged in users can _delete_ their own reviews
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x]  Styling
- [x]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by youknowhu** [comment]
(For my own tracking purposes)
- [x] Users can _read_ reviews for listings
- [x] Logged in users can _create_ reviews
- [x] Logged in users can _update_ their own reviews
- [x] Logged in users can _delete_ their own reviews
- [x] Reviews should be sorted on the back-end
- [X] Displays error if user tries to submit a blank review.
- [x] If logout while form is open, form should close...

**Comment by youknowhu** [comment]
@anastassia-b, 

I **think** this should be ready for review! 

A few things to note, the listings are now at /10 /11 and /12. You should still be able to access the Glacier National Park Listing page by clicking on its photo. 

While the full CRUD cycle of the reviews works it sometimes IS a bit slow, I am not sure if its due to some of my inefficient fetches/messiness, or because of Heroku, but everything SHOULD be functional! 

Kimmy

**Comment by anastassia-b** [comment]
Amazing work!!! All of the functionality and styling is impeccable.
