### ISSUE TITLE
PA Review: Search

### ISSUE THREAD

**Issue by youknowhu** [youknowhu/Hippocampus#8]
- [x] Users can select pre-defined filters that auto-fill search categories.
- [x] Users can filter search categories that immediately change listings and Google Maps results
- [x] Backend: DB, model, controller, views
- [x] Redux Loop: ajax, actions, reducer
- [x] Presentational Components
- [x]  Styling
- [ ]  Smooth, bug-free navigation
- [x]  Adequate and appropriate seeds

**Comment by youknowhu** [comment]
@anastassia-b  this should be ready for review. 
Some things to note 
1) Nav bar search persists on all pages. 
2) Can enter a city in the big search bar in the center of the home page. If you select dates those will persist and auto-fill the booking form. 
3) You can search for a specific city and also apply multiple filters.

**Comment by anastassia-b** [comment]
Excellent job!!! This is the best search implementation I've seen. Amazing.  This MVP is complete.
